# Generated by Django 4.2.3 on 2023-07-29 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social_media.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        default="default_profile_picture.png",
                        upload_to=social_media.models.profile_picture_file_path,
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=65)),
                (
                    "follows",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followed_by",
                        to="social_media.profile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
