# Generated by Django 4.2.3 on 2023-07-29 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0002_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="caption",
            new_name="content",
        ),
    ]
