# Generated by Django 4.2.3 on 2023-08-05 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0006_alter_profile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HashTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=65)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(
                related_name="hashtags", to="social_media.hashtag"
            ),
        ),
    ]
