# Generated by Django 4.2.3 on 2023-08-05 15:37

from django.db import migrations
import imagekit.models.fields
import social_media.models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0007_hashtag_post_hashtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to=social_media.models.image_file_path
            ),
        ),
    ]
