# Generated by Django 4.2.3 on 2023-08-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0008_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="hashtags",
                to="social_media.hashtag",
            ),
        ),
    ]
