# Generated by Django 4.2.3 on 2023-08-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0009_alter_post_hashtag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(
                related_name="hashtags", to="social_media.hashtag"
            ),
        ),
    ]
