# Generated by Django 4.2.3 on 2023-08-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0010_alter_post_hashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="schedule_create",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
